### ISSUE TITLE
Error on lb4 discover

### ISSUE THREAD

**Issue by serininformatica** [strongloop/loopback-connector-ibmi#13]
#   i have this error launching lb4 discover:

```
(node:1049) UnhandledPromiseRejectionWarning: TypeError: IBMiConnector.paginateSQL is not a function
    at IBMiConnector.buildQueryTables (/www/nodejs/lb-vue/node_modules/loopback-connector-ibmi/lib/ibmiconnector.js:1044:26)
    at calls (/www/nodejs/lb-vue/node_modules/loopback-connector/lib/sql.js:1786:23)
    at /www/nodejs/lb-vue/node_modules/async/dist/async.js:2948:28
    at eachOfArrayLike (/www/nodejs/lb-vue/node_modules/async/dist/async.js:500:13)
    at eachOf (/www/nodejs/lb-vue/node_modules/async/dist/async.js:551:16)
    at awaitable (/www/nodejs/lb-vue/node_modules/async/dist/async.js:208:32)
    at /www/nodejs/lb-vue/node_modules/async/dist/async.js:2947:9
    at awaitable (/www/nodejs/lb-vue/node_modules/async/dist/async.js:208:32)
    at Object.parallel$1 [as parallel] (/www/nodejs/lb-vue/node_modules/async/dist/async.js:3029:16)
    at IBMiConnector.SQLConnector.discoverModelDefinitions (/www/nodejs/lb-vue/node_modules/loopback-connector/lib/sql.js:1794:9)
    at DbDataSource.DataSource.discoverModelDefinitions (/www/nodejs/lb-vue/node_modules/loopback-datasource-juggler/lib/datasource.js:1189:20)
    at Object.discoverModelNames (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/lib/model-discoverer.js:21:13)
    at DiscoveryGenerator.discoverModelInfos (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/generators/discover/index.js:152:42)
    at Object.<anonymous> (/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:816:25)
    at /QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
(node:1049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
-bash-4.4$
```

**Comment by markirish** [comment]
(node:1049) UnhandledPromiseRejectionWarning: TypeError: IBMiConnector.paginateSQL is not a function

This is an error I remember encountering before,  but it clearly exists on the object: https://github.com/strongloop/loopback-connector-ibmi/blob/61279f5f2045212714a2defc2295e5bc325e72db/lib/ibmiconnector.js#L1007-L1023

I think I see the issue though. Calls to `paginateSQL` look like ` return IBMiConnector.paginateSQL(sql, 'table_schem', options);`, but `paginateSQL` is not a static member, so it can't be found on the object.

Two possible (exclusive) fixes:
1. Change all calls to `paginateSQL` from `IBMiConnector.paginateSQL` to `this.paginateSQL`
2. Add that static keyword in front of function definition: `static paginateSQL(sql, orderBy, options) {`

The second is probably more correct, but probably won't work because of an internal call to `this.buildLimit` (which itself can probably be static).

You can try to run the first fix on your own `ibmiconnector.js` file and see if it works. I will go through and see if I can't get it cleaned up a bit, but it will be a little before they are merged into the main package.

**Comment by markirish** [comment]
@serininformatica , I fixed this and then had a few more issues, so I fixed those fast too. I am going to play around with it for a little bit to make sure everything is running smooth, and then I will upload a branch for you to test.

**Comment by serininformatica** [comment]
If i try the first fix the result is this error:





*(node:348) UnhandledPromiseRejectionWarning: Error: [IBM][System i Access
ODBC Driver][DB2 for i5/OS]SQL0199 - Parola chiave ORDER non prevista.
Token validi: ( CL END GET SET CALL DROP FREE HOLD LOCK OPEN WITH ALTER.
at
/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/lib/ibmiconnector.js:989:15
  at
/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/odbc/lib/Pool.js:146:9
  at processTicksAndRejections
(internal/process/task_queues.js:79:11)(node:348)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error
originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To
terminate the node process on unhandled promise rejection, use the CLI flag
`--unhandled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode
<https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode>).
(rejection id: 1)(node:348) [DEP0018] DeprecationWarning: Unhandled promise
rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.*



Luca Fabbriciani
Serin Informatica


Il giorno ven 15 mag 2020 alle ore 15:41 Mark Irish <
notifications@github.com> ha scritto:

**Comment by markirish** [comment]
Looks like we wrote at the same time! I found that bug and fixed it as well, I will upload my fixes today for you to test out.

**Comment by serininformatica** [comment]
tx
Luca Fabbriciani
Serin Informatica


Il giorno ven 15 mag 2020 alle ore 17:59 Mark Irish <
notifications@github.com> ha scritto:

**Comment by markirish** [comment]
Ok, it should be available on the `fix-discovery` branch: `npm install strongloop/loopback-connector-ibmi#fix-discovery`

The underlying dependency on `odbc` hasn't been updated, so make sure that you retain the beta version of `2.3.0` if you are doing UNICODE. Early next week I plan to release `2.3.0` out of beta, and then I will update the dependency at the same time as I push the fixes for discovery.

Let me know how it goes!

**Comment by serininformatica** [comment]
now I get this error, but the process goes on and the model is generated





























*-bash-4.4$ /QOpenSys/pkgs/lib/nodejs12/bin/lb4 discover --schema VUE?
Select the connector to discover dbTrace: SELECT TABLE_TYPE AS "type",
TABLE_NAME AS "name",    TABLE_SCHEMA AS "owner" FROM QSYS2.SYSTABLES
WHERE TABLE_SCHEMA = 'VUE' AND  table_type = 'T' ORDER BY TABLE_SCHEMA,
TABLE_NAME           at IBMiConnector.executeSQL
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/lib/ibmiconnector.js:966:13)
  at
/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/loopback-connector/lib/sql.js:597:10
  at
/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/observer.js:278:9
  at doNotify
(/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/observer.js:157:49)
  at IBMiConnector.ObserverMixin._notifyBaseObservers
(/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/observer.js:180:5)
  at IBMiConnector.ObserverMixin.notifyObserversOf
(/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/observer.js:155:8)
  at IBMiConnector.ObserverMixin.notifyObserversAround
(/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/observer.js:230:15)
  at IBMiConnector.SQLConnector.execute
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/loopback-connector/lib/sql.js:596:8)
  at calls
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/loopback-connector/lib/sql.js:1786:10)
  at
/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:2948:28
  at eachOfArrayLike
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:500:13)
  at eachOf
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:551:16)
  at awaitable
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:208:32)
  at
/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:2947:9
  at awaitable
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:208:32)
  at Object.parallel$1 [as parallel]
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/async/dist/async.js:3029:16)
  at IBMiConnector.SQLConnector.discoverModelDefinitions
(/www/nodejs/lb-contracts/node_modules/loopback-connector-ibmi/node_modules/loopback-connector/lib/sql.js:1794:9)
  at DbDataSource.DataSource.discoverModelDefinitions
(/www/nodejs/lb-contracts/node_modules/loopback-datasource-juggler/lib/datasource.js:1189:20)
  at Object.discoverModelNames
(/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/lib/model-discoverer.js:21:13)
  at DiscoveryGenerator.discoverModelInfos
(/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/generators/discover/index.js:152:42)
  at Object.<anonymous>
(/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/node_modules/yeoman-generator/lib/index.js:816:25)
  at
/QOpenSys/pkgs/lib/nodejs12/lib/node_modules/@loopback/cli/node_modules/run-async/index.js:49:25*

Il giorno ven 15 mag 2020 alle ore 20:40 Mark Irish <
notifications@github.com> ha scritto:

**Comment by markirish** [comment]
That is actually a trace that I have printing (and forgot to take out). So if the model is generated, then that's great!

**Comment by serininformatica** [comment]
Yeah!! Fantastic!! Thank you very much
Luca Fabbriciani
Serin Informatica


Il giorno sab 16 mag 2020 alle ore 16:02 Mark Irish <
notifications@github.com> ha scritto:
