### ISSUE TITLE
Error on CCSID=1208

### ISSUE THREAD

**Issue by serininformatica** [strongloop/loopback-connector-ibmi#14]
Error on iseries if i configure
`"connectionString": "DSN=*LOCAL;CCSID=1208"`

**Comment by markirish** [comment]
Can I close this per: https://github.com/markdirish/node-odbc/issues/79#issuecomment-628215343 ?

**Comment by serininformatica** [comment]
yes, thank a lot
Luca Fabbriciani
Serin Informatica


Il giorno ven 15 mag 2020 alle ore 15:30 Mark Irish <
notifications@github.com> ha scritto:
