### ISSUE TITLE
Connection works only with existing DSN in connectionString

### ISSUE THREAD

**Issue by JoergFechner** [strongloop/loopback-connector-ibmi#17]
# Description/Steps to reproduce
A connection only works with an existing DNS in the connectionString.
"connectionString": "DSN=IBM i e-ins;UID=wurst;PWD=hannes;"

This does not work:
"connectionString": "DRIVER=IBM i Access ODBC Driver;SERVER=10.xxx.xxx.xx;UID=wurst;PWD=hannes;DBQ=lib1,lib2"

# Expected result
Establish a connection without DSN, but with any parameter provided by IBM
See [IBM Documentation](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzaik/connectkeywords.htm)

# Additional information
Tested on WIndows 10

It would be nice to provide a configuration object with any parameter as mentioned above and the connector creates the connection-string

**Comment by markirish** [comment]
There is a mistake in your connection string: `SERVER` is not a valid connection string key, it should be `SYSTEM`: 

```
DRIVER=IBM i Access ODBC Driver;SYSTEM=10.xxx.xxx.xx;UID=wurst;PWD=hannes;DBQ=lib1,lib2
```

"It would be nice to provide a configuration object with any parameter as mentioned above and the connector creates the connection-string"

So are you saying a configuration object like 
```
{
  DRIVER: "IBM i Access ODBC Driver",
  SYSTEM: "my.system.location",
  DBQ: "Lib1,Lib2",
  ...
}
```
I think the main problem with that would be making sure that the list of options remains consistent with all of the connection string options, as well as the overhead of building the string by iterating over all of the options. I will look into it though.


Hope that helps!

**Comment by JoergFechner** [comment]
Hello Mark,

thank you you for your reply.
Couldn't believe that I have overseen it.

Thank you.

But, one question. 

Do you have an idea, how deal with LoopBack and composite keys of a table on IBM i?
