### ISSUE TITLE
[IBM][System i Access ODBC Driver]Communication link failure. comm rc=10054 - CWBCO1047 - The IBM i server application  disconnected the connection

### ISSUE THREAD

**Issue by JoergFechner** [strongloop/loopback-connector-ibmi#18]
# Description/Steps to reproduce

After several minutes of inactivity I get this error.

Unhandled error in GET /spartenstamm/meta: 500 Error: [IBM][System i Access ODBC Driver]Communication link failure. comm rc=10054 - CWBCO1047 - The IBM i server application  disconnected the connection
    at C:\workspace\phpstorm\compass\backend\node_modules\loopback-connector-ibmi\lib\ibmiconnector.js:989:15
    at C:\workspace\phpstorm\compass\backend\node_modules\odbc\lib\Pool.js:152:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

# Link to reproduction sandbox
not available

# Expected result
connect silently again to avoid error

# Additional information

**Comment by JoergFechner** [comment]
Any hints to prevent this issue?

**Comment by kadler** [comment]
@JoergFechner 10054 is "Connection reset by peer", so it seems like something to look at from the IBM i side, since it's the one dropping the connection (or possibly a firewall gone awry).

**Comment by markirish** [comment]
Looks like there is a relatively ancient issue on the `odbc` issue board for the same problem that we (I) never resolved: https://github.com/markdirish/node-odbc/issues/63

**Comment by JoergFechner** [comment]
Yes it is somewhat „old“. 

The only thing that helped, was putting the server with loopback right next to the iSeries. 

Any connection from outside causes issues with the firewall and de- and encryption of the packages …

 

 

Von: Mark Irish ***@***.***> 
Gesendet: Mittwoch, 14. Juli 2021 17:19
An: loopbackio/loopback-connector-ibmi ***@***.***>
Cc: Joerg Fechner ***@***.***>; Mention ***@***.***>
Betreff: Re: [loopbackio/loopback-connector-ibmi] [IBM][System i Access ODBC Driver]Communication link failure. comm rc=10054 - CWBCO1047 - The IBM i server application disconnected the connection (#18)

 

Looks like there is a relatively ancient issue on the odbc issue board for the same problem that we (I) never resolved: markdirish/node-odbc#63 <https://github.com/markdirish/node-odbc/issues/63>

**Comment by jenders-polar** [comment]
I am experiencing this when I try to make a few dozen requests at the same time.
