### ISSUE TITLE
Requests block each other

### ISSUE THREAD

**Issue by JoergFechner** [strongloop/loopback-connector-ibmi#19]
# Requests block each other
In the application we fire two asynchronous requests. 

The time for a response is
Request 1 = 5.70 sec
Request 2 = 7.29 sec

If I only copy the url for the Request and put it into the browser I get the following response
Request 1 = 1.26 sec
Request 2 = 5.76 sec

# Link to reproduction sandbox
not possible to do that

# Expected result
similar response time in the application

**Comment by JoergFechner** [comment]
Does anybody has a solution for this problem?

**Comment by markirish** [comment]
Are these the very first requests you make? The previous version of the underlying ODBC connector had a very long pool start up time. It would create all 10 connections _before_ letting any queries run. The new version (2.4.0) creates one connection, then starts letting queries run while it creates the other 9 on a separate thread. This _might_ fix your issue, and when #20 gets merged in you should be able to just update and check.
