### ISSUE TITLE
Update copyright header for the correct module name

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-ibmi#2]
In various files, the copyright headers are not referring the module name as `loopback-connector-ibmi`.  for example, https://github.com/strongloop/loopback-connector-ibmi/blob/master/lib/globalize.js#L2.

To fix it, you can:
- install `strong-tools` module. https://www.npmjs.com/package/strong-tools
- run `slt copyright` command. 

One thing to note is that it takes `author` value from the package.json.  It can be set as:
```
"author": "IBM Corp.",
```

as shown in here: https://github.com/strongloop/loopback-connector-mongodb/blob/master/package.json#L8.

**Comment by markirish** [comment]
Fixed with PR #4
